language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c95f2ea812629db105b9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
